### ISSUE TITLE
feat: dark mode

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/dtube#3]

**Comment by r-Dev03** [comment]
is adding a dark mode all that is needed? if so I would like to take on this issue
@akhileshthite

**Comment by akhileshthite** [comment]
> is adding a dark mode all that is needed? if so I would like to take on this issue @akhileshthite

Hey @r-Dev03,
Go ahead.

**Comment by Karan0009** [comment]
Is this issue resolved? If not i would like to take this.

**Comment by akhileshthite** [comment]
> Is this issue resolved? If not i would like to take this.

@r-Dev03 ?

**Comment by r-Dev03** [comment]
You can go ahead and take it, I have not had the time to tackle it.

**Comment by akhileshthite** [comment]
> Is this issue resolved? If not i would like to take this.

Go ahead ✌️

**Comment by Karan0009** [comment]
okay! 👌

**Comment by Karan0009** [comment]
@akhileshthite can you please review the PR

**Comment by akhileshthite** [comment]
> @akhileshthite can you please review the PR

Yes, will review today.

**Comment by akhileshthite** [comment]
> @akhileshthite can you please review the PR

Great work.
