### ISSUE TITLE
feat: upgrade to react hooks

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/dtube#4]
The main branch of DTube uses react classes because the initial [educational tutorial](https://learn.figment.io/tutorials/build-a-social-media-dapp-and-deploy-it-on-polygon) was written with react classes. However, if you want to work on this issue, then please `fork` the main branch and `push` your changes to [react-hooks](https://github.com/akhileshthite/dtube/tree/react-hooks) branch and send a [pull request](https://github.com/akhileshthite/dtube/pulls) for the same.
Later, we can create a [production](https://github.com/akhileshthite/dtube/tree/production) build for better performance.

**Comment by nertokul** [comment]
Hello @akhileshthite , I would like to work on this issue.

**Comment by akhileshthite** [comment]
> Hello @akhileshthite , I would like to work on this issue.

Hey,
Sure, go ahead.

**Comment by nertokul** [comment]
> > Hello @akhileshthite , I would like to work on this issue.
> 
> Hey, Sure, go ahead.

thanks, I am on it.

**Comment by Nis7538** [comment]
Hello @akhileshthite, I would like to work on this issue. Can you assign the issue to me?
